services:
  mongodb:
    image: mongo:8
    ports:
     - 27017:27017
    environment:
     - MONGO_INITDB_ROOT_USERNAME=admin
     - MONGO_INITDB_ROOT_PASSWORD=password
  mongo-express:
    image: mongo-express:1.0.2
    restart: always  # fixes MongoNetworkError when MongoDB is not ready when Mongo Express starts
    ports:
     - 8081:8081
    environment:
     - ME_CONFIG_MONGODB_AUTH_USERNAME=admin
     - ME_CONFIG_MONGODB_AUTH_PASSWORD=password
     - ME_CONFIG_MONGODB_SERVER=mongodb